config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  get 'languages/index'
  post 'languages/destroy_logo'

  post 'snippets/:id/update_active', to: 'snippets#update_active'
  post 'snippets/:id/update_snippet', to: 'snippets#update_snippet'
  post 'snippets/:id/add_snippet', to: 'snippets#add_snippet'
  post 'categories/:id/update_active', to: 'categories#update_active'


  get 'categories/index'

  get 'study/index'

  get 'quizzes/index'
  get 'quizzes/new', to: 'quizzes#new'
  get 'quizzes/question', to: 'quizzes#question'
  get 'quizzes/manage', to: 'quizzes#manage'
  get 'quizzes/answer', to: 'quizzes#answer'
  get 'welcome/index'

  resources :snippets

  resources :languages

  resources :categories

  resources :quizzes

  root 'quizzes#new'
  #get '/quizzes', to: 'controller_name#press'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user

  validates :title, :user, presence: true
  validates :title, length: { in: 1..50 }, uniqueness: { scope: :user_id }
  validates :runtime_complexity, length: { maximum: 30 }
  validates :space_complexity, length: { maximum: 30 }

  has_many :implementations, inverse_of: :snippet, :dependent => :destroy
  has_many :quiz_snippets

  accepts_nested_attributes_for :implementations, allow_destroy: true

  after_create :init

  def init
    self.active  ||= true   #will set the default value only if it's nil
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
    before_filter :authenticate_user!
    include ApplicationHelper

    def index
      authorize! :index, Snippet
      # Snippets to list
      @snippets = Snippet.accessible_by(current_ability).order('created_at')
      # Snippets to display at bottom of sync list
      @unowned_snippets = get_unowned_snippets

      unowned_exists = @unowned_snippets.exists?
      updated_exists = !@snippets.find_by(:update_available => true).blank?
      modified_exists = !@snippets.where(:modified => true).find_by(:default => true).blank?

      # color of FAB button
      @color = "grey"
      if (updated_exists || unowned_exists) && !current_user.admin
        @color = "green"
      elsif modified_exists  && !current_user.admin
        @color = "blue"
      end
    end

    def show
      @snippet = Snippet.accessible_by(current_ability).find(params[:id])
      @category = Category.accessible_by(current_ability).find_by_id(@snippet.category_id)
      @implementations = @snippet.implementations
      authorize! :new, @snippet
    end

    def new
      @snippet = Snippet.new
      authorize! :new, @snippet

      build_implementations
    end

    def create
      @snippet = Snippet.new(snippet_params)
      @snippet.user = current_user
      @snippet.default = false
      authorize! :create, @snippet

      if @snippet.save
        #If admin we need to store data to be used later for default snippet look up
        if current_user.admin == true
          # @snippet.default = true;
          @snippet.update_attributes(
            :default => true,
            :default_id => @snippet.id
            )
        end

        redirect_to snippets_path
      else
        build_implementations
        @errors = @snippet.errors
        render 'new'
      end
    end

    def edit
      @snippet = Snippet.accessible_by(current_ability).find(params[:id])
      authorize! :edit, @snippet
      @implementations = @snippet.implementations
      add_new_implementations
    end

    def update
      @snippet = Snippet.find(params[:id])
      authorize! :update, @snippet

      #If admin we need to store data to be used later for default snippet look up
      if current_user.admin == true
        # Get all snippets that should be marked available for update, that are default and not owned by admin
        to_update_snippets = Snippet.where(default: true).where(default_id: @snippet.id).where.not(user: current_user).update_all(update_available: true)
      else
        # If current user is not admin then set snippet to modified, admins don't need modified to be set because they are the admin and they own the definitive version of the snippet
        @snippet.modified = true
      end

      if @snippet.update(snippet_params)
        redirect_to snippets_path
      else
        @errors = @snippet.errors
        render 'edit'
      end
    end

    def destroy
      @snippet = Snippet.find(params[:id])
      authorize! :destroy, @snippet
      @snippet.destroy

      redirect_to snippets_path
    end

    def update_active
      @snippet = Snippet.find(params[:id])

      # if @snippet.update_attributes(:active => params[:active])
      if @snippet.update_attributes(:active => params[:active])
        # data = {:message => "Worked! " + params[:active]}
        # render :json => data, :status => :ok
      else
        # data = {:message => "Not worked! " + params[:active]}
        # render :json => data, :status => :ok
      end
    end

    #TODO: Should be moved to private

    def update_snippet
      snippet = Snippet.find(params[:id])
      default_snippet = Snippet.find(snippet.default_id)
      cloned_snippet = default_snippet.deep_clone include: [:implementations]
      cloned_snippet.user = current_user
      cloned_snippet.default_id = default_snippet.id

      # Unless there is no category assigned
      unless default_snippet.category_id == nil
        # Unless their already exists a record with the category_id we are going to add
        unless current_user.categories.where(default_id: default_snippet.category_id).exists?
          # clone the snippet with category_id
          cloned_snippet.category_id = add_category(default_snippet.category_id)
        else
          # make it the same id as the original snippet to avoid duplication
          cloned_snippet.category_id = current_user.categories.where(default_id: default_snippet.category_id).first.id
          # cloned_snippet.category_id = current_user.categories.find(:id, :conditions => [ "user_name = ?", user_name])
        end
      end

      # cloned_snippet.category_id = add_category(default_snippet.category_id)
      add_languages

      cloned_snippet.implementations.each do |implementation|
        # Get the id of the language owned by the current user that has a default_id equivalent to the implementations language id
      implementation.language_id = Language.where(user_id: current_user.id).where(default_id: implementation.language_id).first.id
    end
    # delete before or else validation will fail for duplicate titles
    p "destroy"
    snippet.destroy
    if cloned_snippet.save!
      p "Snippet updated successfully"
      @updated_snippet = cloned_snippet
      render :json => @updated_snippet
    else
      p "Snippet failed to update"
    end
  end

  def add_snippet
    default_snippet = Snippet.find(params[:id])
    cloned_snippet = default_snippet.deep_clone include: [:implementations]
    cloned_snippet.user = current_user
    cloned_snippet.default_id = default_snippet.id

    # Unless there is no category assigned
    unless default_snippet.category_id == nil
      # Unless their already exists a record with the category_id we are going to add
      unless current_user.categories.where(default_id: default_snippet.category_id).exists?
        # clone the snippet with category_id
        cloned_snippet.category_id = add_category(default_snippet.category_id)
      else
        # make it the same id as the original snippet to avoid duplication
        cloned_snippet.category_id = current_user.categories.where(default_id: default_snippet.category_id).first.id
        # cloned_snippet.category_id = current_user.categories.find(:id, :conditions => [ "user_name = ?", user_name])
      end
    end

    # cloned_snippet.category_id = add_category(default_snippet.category_id)
    add_languages

    cloned_snippet.implementations.each do |implementation|
      # Get the id of the language owned by the current user that has a default_id equivalent to the implementations language id
      implementation.language_id = Language.where(user_id: current_user.id).where(default_id: implementation.language_id).first.id
    end

    if cloned_snippet.save!
      p "Snippet added successfully"
      @added_snippet = cloned_snippet
      render :json => @added_snippet
    else
      p "Snippet failed to be added"
    end
  end

  private
    def build_implementations
      languages = Language.accessible_by(current_ability)

      @implementations = []
      # Create blank implementations to be used in new view
      languages.each do |language|
        implementation = @snippet.implementations.build
        implementation.language_id = language.id
        @implementations << implementation
      end
    end

    def add_languages
      admin = User.where('admin = ?', true).first

      default_admin_languages = admin.languages.where(:default => true);
      default_user_languages = current_user.languages.where(:default => true);

      to_add_languages = default_admin_languages
      user_languages = default_user_languages.pluck(:default_id).uniq

      if !user_languages.empty?
        to_add_languages = to_add_languages.where('id NOT IN (?)', user_languages)
      else
        to_add_languages = default_admin_languages
      end

      to_add_languages.each do |language|
        cloned_language = language.deep_clone
        cloned_language.user = current_user
        cloned_language.logo = language.logo
        if cloned_language.save!
          p "Language saved successfully"
        else
          p "Language failed to save"
        end
      end
    end

    def add_category(id)
      category = Category.find(id)
      cloned_category = category.deep_clone
      cloned_category.user = current_user
      if cloned_category.save!
        p "Category saved successfully"
        cloned_category.id
      else
        p "Category failed to save"
      end
    end

    # Gets all of the snippets that are owned by the admin but not owned by the user
    def get_unowned_snippets
      admin = User.find_by admin: true
      admin_snippets = Snippet.where(:default => true).where(:user => admin)
      users_default_snippets = Snippet.accessible_by(current_ability).where(:default => true)

      unowned_snippets = admin_snippets
      user_snippets = users_default_snippets.pluck(:default_id).uniq
      if !user_snippets.empty?
        unowned_snippets = unowned_snippets.where('id NOT IN (?)', user_snippets)
      else
        unowned_snippets = admin_snippets
      end
      unowned_snippets.each do |unowned_snippet|
        p unowned_snippet.inspect
      end
      unowned_snippets
    end

    def add_new_implementations
      languages = Language.accessible_by(current_ability)
      implemented_languages = @implementations.pluck(:language_id).uniq

      languages.each do |language|
        if !implemented_languages.include? language.id
          implementation = Implementation.new()
          implementation.language_id = language.id
          # TODO: Get actual code from admin
          implementation.code = ""
          implementation.snippet_id = @snippet.id
          if implementation.save

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>
  <div class="row">
    <div class="section input-field col s5 m3 offset-s1 offset-m1 offset-l2">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="section input-field col s5 m3 offset-s1 offset-m1 offset-l2">
      <%= collection_select(:snippet, :category_id, Category.accessible_by(current_ability), :id, :name,  {:include_blank=>'No Category'}, {:include_blank=>'Nothing selected', :class=>'materialize-select category-select'} ) %>
    </div>
  </div>
  <div class="row no-margin">
    <script src="https://cdn.jsdelivr.net/ace/1.2.6/min/ace.js" type="text/javascript" charset="utf-8"></script>
    <div id="snippet-editor-parent" class="snippet-editor-parent col s12 m10 offset-m1 l8 offset-l2">
      <div class="editor-header">
        <div class="languages">
          <% @implementations.each do |implementation| %>
            <% language = get_language(implementation, @snippet.id) %>
            <div id="language-tab-<%= language.id %>" class="language with-image" data-langid="<%= language.id %>">
              <div class="abr"><span><%= language.name[0..1] %></span></div>
              <%= image_tag language.logo.url, :onerror => 'imgError(this);', :data => {:language => language.name, :langid => language.id } %>
            </div>
          <% end %>
        </div>
      </div>
      <%= f.fields_for :implementations do |f| %>
        <% language = get_language(f.object, @snippet.id) %>
        <%= f.text_area :code, :id => "editor-#{language.id}", :class => 'code-field' %>
        <div id="ace-editor-<%= language.id %>" class="editor" data-language="<%= language.name %>"><%= f.object.code %></div>
        <%=
        # TODO: REMOVE language field, need data?
        f.hidden_field :language_id, :value => language.id, :data => { :language => language.id } %>
        <script>
          $(document).ready(function() {
            initializeEditor(ace.edit("ace-editor-<%= language.id %>"), <%= language.id %>, "<%= language.name %>");
          });
        </script>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s4 m3 offset-s1 offset-m1 offset-l2">
      <%= f.label :runtime_complexity %><br>
      <%= f.text_field :runtime_complexity %>
    </div>
    <div class="input-field col s4 m3 ">
      <%= f.label :space_complexity %><br>
      <%= f.text_field :space_complexity %>
    </div>
  </div>
  <div class="row">
    <div class="col s10 offset-s1 offset-m1 offset-l2 ">
      <%= f.button :class => 'btn-large waves-effect waves-light blue white-text btn btn-flat'%>
    </div>
  </div>
<% end %>
<%= render :partial => "layouts/save_modal" %>

app/views/snippets/edit.html.erb
<% content_for :title, "Edit Snippet" %>
<div id="content" class="container snippet">
  <div class="row no-margin">
    <h2 class="section-header no-padding col s8 m6  offset-s1 offset-m1 offset-l2">Edit Code Snippet</h2>
  </div>

  <%= render 'form' %>

  <div class="row no-margin">
    <div class="col s12 m10 offset-m1 l8 offset-l2 snippet-back-link">
      <%= link_to '&larr; Back'.html_safe, snippets_path %>
    </div>
  </div>
</div>

app/views/snippets/index.html.erb
<% content_for :title, "Manage Snippets" %>
<div class="container snippet index" id="content">
  <h2 class="section-header center-align">Snippets</h2>
  <table id="snippets-index-table" class="highlight centered">
    <thead>
      <tr>
        <th>Title</th>
        <!-- TODO: Num Supported Languages -->
        <th>Category</th>
        <th>Version</th>
        <th>Languages</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @snippets.each do |snippet| %>
      <tr data-id="<%= snippet.id %>">
        <td><%= snippet.title %></td>
        <td><%= get_snippet_category(snippet) %></td>
        <td><%= get_customization_status(snippet) %></td>
        <td><%= get_implementation_count(snippet) %></td>
        <td class="min-width"><%= link_to 'Show', snippet_path(snippet) %></td>
        <td class="min-width"><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td class="min-width"><%= link_to 'Remove', snippet_path(snippet),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </br>
  <div class="row center">
    <div class="col s12 buttons">
      <%= link_to 'New snippet', new_snippet_path, :class => 'btn-large waves-effect waves-light blue' %>
      <a class="sync-button btn-floating btn-large waves-effect waves-light <%= @color %>"><i class="material-icons">loop</i></a>
    </div>
  </div>
  <div class="row no-margin">
    <div class="col s12">
      <%= link_to '&larr; Back'.html_safe, {controller: 'quizzes', action: 'manage'}, :class => "manage-back-link"  %>
    </div>
  </div>
  <!-- Modal Structure -->
  <div class="modal sync-modal">
    <div class="modal-header">
      <h3 class="section-header white-text">Sync Default Snippets</h3>
    </div>
    <div class="modal-content">
      <table id="snippets-sync-table">
        <% @snippets.each do |snippet| %>
          <% if snippet.default == true %>
            <tr data-id="<%= snippet.id %>">
              <td class="snippet-name">
                <%= snippet.title %>
              </td>
              <td class="min-width">
                <% if snippet.update_available %>
                  <a class="update-button waves-effect waves-light btn" data-value="<%= snippet.id %>">Update</a>
                <% elsif snippet.modified %>
                  <a class="reset-button waves-effect waves-light btn" data-value="<%= snippet.id %>">Reset</a>
                <% else %>
                  <a class="default-button waves-effect waves-light btn btn-flat" data-value="">Default</a>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
        <% @unowned_snippets.each do |snippet| %>
          <% if snippet.default == true %>
            <tr>
              <td class="snippet-name">
                <%= snippet.title %>
              </td>
              <td class="min-width">
                <a class="add-button waves-effect waves-light btn" data-value="<%= snippet.id %>">Add</a>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect btn-flat">Done</a>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $("a.update-button, a.reset-button").click(function(){
      button = $(this);
      $.ajax({
        url: '/snippets/'+$(this).data("value")+'/update_snippet',
        type: 'POST',
        success: function(data,status,xhr){
          console.log(data);
          updateSnippetsPage(button, "default", data);
        },
        error: function(xhr,status,error){
          console.log(xhr);
          alert(error);
        }
      });
    });

    $("a.add-button").click(function(){
      button = $(this);
      $.ajax({
        url: '/snippets/'+$(this).data("value")+'/add_snippet',
        type: 'POST',
        success: function(data,status,xhr){
          console.log(data);
          updateSnippetsPage(button, "default", data);
        },
        error: function(xhr,status,error){
          console.log(xhr);
          alert(error);
        }
      });
    });

    function updateSnippetsPage(button, action, record){
      if(button.hasClass("update-button") || button.hasClass("reset-button") ){
        $("#snippets-index-table tr[data-id=" + button.data("value") + "]").remove();
        $("#snippets-sync-table tr[data-id=" + button.data("value") + "] .snippet-name").text(record.title);
      }

      button.text(action);
      button.removeClass("update-button add-button reset-button default-button");
      button.addClass(action + "-button btn-flat");

      var tile = "<td>" + record.title + "</td>";
      var runtime_complexity = "<td>" + record.runtime_complexity + "</td>";
      var space_complexity = "<td>" + record.space_complexity + "</td>";
      var implemented = "<td>" + "</td>";
      var show = '<td class="min-width">' + '<a href="/snippets/' + record.id + '">Show</a>' + '</td>';
      var edit = '<td class="min-width">' + '<a href="/snippets/' + record.id + '/edit">Edit</a>' + '</td>';
      var destroy = '<td class="min-width"><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/snippets/' + record.id + '">Destroy</a></td>';
      $('#snippets-index-table tr:last').after('<tr ' +  'data-id="' + button.data("value") + '"> ' + tile + runtime_complexity + space_complexity + implemented + show + edit + destroy + ' </tr>');

      var sync_table_buttons = $('#snippets-sync-table .btn');
      if(!sync_table_buttons.hasClass("reset-button") && !sync_table_buttons.hasClass("update-button") && !sync_table_buttons.hasClass("add-button")){
        // If all the buttons are default, make the sync button grey
        $('.sync-button').removeClass("green blue");
        $('.sync-button').addClass("grey");
      }else if (sync_table_buttons.hasClass("reset-button") && !sync_table_buttons.hasClass("update-button") && !sync_table_buttons.hasClass("add-button")) {
        // If the only buttons left are reset buttons, make the sync button blue
        $('.sync-button').removeClass("grey green");
        $('.sync-button').addClass("blue");
      }

    }
  });

</script>

app/views/snippets/new.html.erb
<% content_for :title, "Create New Snippet" %>
<div id="content" class="container snippet">
  <div class="row no-margin">
    <h2 class="section-header no-padding col s8 m6  offset-s1 offset-m1 offset-l2">New Code Snippet</h2>
  </div>

  <%= render 'form' %>

  <div class="row no-margin">
    <div class="col s12 m10 offset-m1 l8 offset-l2 snippet-back-link">
      <%= link_to '&larr; Back'.html_safe, snippets_path %>
    </div>
  </div>
</div>

app/views/snippets/show.html.erb
<% content_for :title, "View #{@snippet.title}" %>
<div class="container snippet" id="content">
  <div class="row no-margin">
    <div class="col s8 m6  offset-s1 offset-m1 offset-l2">
      <h2 class="section-header"><%= @snippet.title %><span class="snippet-category-label"><% unless @category.blank? %>- <%= @category.name %><% end %></span></h2>
    </div>
    <div class="col s2">
      <div class="options">
        <%= link_to 'Edit', edit_snippet_path(@snippet), class: "option" %>
        <%= link_to 'Remove', snippet_path(@snippet),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "option" %>
      </div>
    </div>
  </div>
  <div class="row no-margin">
    <script src="https://cdn.jsdelivr.net/ace/1.2.6/min/ace.js" type="text/javascript" charset="utf-8"></script>
    <div id="snippet-editor-parent" class="snippet-editor-parent col s12 m10 offset-m1 l8 offset-l2">
      <div class="editor-header">
        <div class="languages">
          <% @implementations.each do |implementation| %>
            <% language = get_language(implementation, @snippet.id) %>
            <div id="language-tab-<%= language.id %>" class="language with-image" data-langid="<%= language.id %>">
              <div class="abr"><span><%= language.name[0..1] %></span></div>
              <%= image_tag language.logo.url, :onerror => 'imgError(this);', :data => {:language => language.name, :langid => language.id } %>
            </div>
          <% end %>
        </div>
      </div>
      <% @implementations.each do |implementation| %>
        <% language = get_language(implementation, @snippet.id) %>
        <div id="ace-editor-<%= language.id %>" class="editor" data-language="<%= language.name %>"><%= implementation.code %></div>
        <script>
          $(document).ready(function() {
            initializeEditor(ace.edit("ace-editor-<%= language.id %>"), <%= language.id %>, "<%= language.name %>");
            ace.edit("ace-editor-<%= language.id %>").setReadOnly(true);
            ace.edit("ace-editor-<%= language.id %>").setHighlightActiveLine(false);
          });
        </script>
      <% end %>
    </div>
  </div>
  <div class="row data-fields">
    <div class="input-field col s4 m4 l4 offset-s2 offset-m2 offset-l3">
      <span class="data-label">Runtime Complexity</span><br>
      <span class="data-field"><%= @snippet.runtime_complexity %></span>
    </div>
    <div class="input-field col s4 m4 l4">
      <span class="data-label">Space Complexity</span><br>
      <span class="data-field"><%= @snippet.space_complexity %></span>
    </div>
    <div class="col s12 m10 offset-m1 l8 offset-l2 snippet-back-link">
      <%= link_to '&larr; Back'.html_safe, snippets_path %>
    </div>
  </div>
</div>