config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  get 'languages/index'
  post 'languages/destroy_logo'

  post 'snippets/:id/update_active', to: 'snippets#update_active'
  post 'snippets/:id/update_snippet', to: 'snippets#update_snippet'
  post 'snippets/:id/add_snippet', to: 'snippets#add_snippet'
  post 'categories/:id/update_active', to: 'categories#update_active'


  get 'categories/index'

  get 'study/index'

  get 'quizzes/index'
  get 'quizzes/new', to: 'quizzes#new'
  get 'quizzes/question', to: 'quizzes#question'
  get 'quizzes/manage', to: 'quizzes#manage'
  get 'quizzes/answer', to: 'quizzes#answer'
  get 'welcome/index'

  resources :snippets

  resources :languages

  resources :categories

  resources :quizzes

  root 'quizzes#new'
  #get '/quizzes', to: 'controller_name#press'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user

  validates :name, :user, presence: true
  validates :name, length: { in: 1..20}, uniqueness: { scope: :user_id }

  has_many :implementations, inverse_of: :language, :dependent => :destroy

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, presence: true,
    :content_type => { :content_type => /\Aimage/ },
    size: { in: 0..300.kilobytes }
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, Language
    @languages = Language.accessible_by(current_ability)
  end

  def show
    # @language = Language.find(params[:id])
    redirect_to languages_path
  end

  def new
    @language = Language.new
    authorize! :new, @language
  end

  def create
    @language = Language.new(language_params)
    @language.user = current_user
    @language.default = false
    authorize! :create, @language

    if @language.save

      #If admin we need to store data to be used later for default language look up
      if current_user.admin == true
        @language.default = true;
        @language.update_attributes(
          :default => true,
          :default_id => @language.id
          )
      end

      @languages = Language.accessible_by(current_ability)
      redirect_to languages_path
    else
      @language.errors.delete(:logo_file_size)
      @errors = @language.errors
      render 'new'
    end
  end

  def edit
    @language = Language.find(params[:id])
    authorize! :edit, @language
  end

  def update
    @language = Language.find(params[:id])
    authorize! :update, @language

    if @language.update(language_params)
      @languages = Language.accessible_by(current_ability)

      redirect_to languages_path
    else
      @errors = @language.errors
      render 'edit'
    end
  end

  def destroy
    @language = Language.find(params[:id])

    if @language.destroy
      p "Successfully destroyed language"
    else
      p "Unsuccessfully destroyed language"
    end

    redirect_to languages_path
  end

  private
    def language_params
      params.require(:language).permit(:name, :logo)
    end
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language, :html => { :multipart => true }) do |f| %>
  <div class="row">
    <div class="section input-field col s8 m6 l4 offset-s1 offset-m1 offset-l2">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="no-padding section input-field col s10 offset-s1 offset-m1 offset-l2">
        <label for="language_logo" class="custom-file-upload">Choose File
          <img id="preview_logo_unloaded" src="#" alt="your image" />
          <% if @language.logo.exists? %>
            <%= image_tag @language.logo.url(:thumb), :id => 'preview_logo' %>
          <% end %>
        </label>
        <%= f.file_field :logo %>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col s10 offset-s1 offset-m1 offset-l2">
      <%= f.button :class => 'btn-large waves-effect waves-light blue white-text btn btn-flat'%>
    </div>
  </div>
<% end %>

app/views/languages/edit.html.erb
<% content_for :title, "Edit Language" %>
<div id="content" class="container language">
  <div class="row no-margin">
    <h2 class="section-header col s10 m10  offset-s1 offset-m1 offset-l2">Edit Language</h2>
  </div>

  <%= render 'form' %>

  <div class="row">
    <div class="col s10  offset-s1 offset-m1 offset-l2">
      <%= link_to '&larr; Back'.html_safe, languages_path %>
    </div>
  </div>
</div>

app/views/languages/index.html.erb
<% content_for :title, "Manage Languages" %>
<div class="container language" id="content">
  <h2 class="section-header center-align">Languages</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th data-field="name">Name</th>
        <th data-field="logo">Logo</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody class="languages">
      <% @languages.each do |language| %>
        <tr>
          <td><span class="name"><%= language.name %></span></td>
          <td><span style="display: none" class="text-version logo has-image" data-langid="<%= language.id %>"><%= language.name[0..1] %></span><%= image_tag language.logo.url, :class => "image-version logo", :onerror => 'imgIndexError(this);', :data => {:language => language.name, :langid => language.id } %></td>
          <td class="min-width"><%= link_to 'Edit', edit_language_path(language) %></td>
          <td class="min-width"><%= link_to 'Remove', language_path(language),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </br>
  <div class="row center">
    <div class="col s12">
      <%= link_to 'New Language', new_language_path, :class => 'btn-large waves-effect waves-light blue' %>
    </div>
  </div>
  <div class="row no-margin">
    <div class="col s12">
      <%= link_to '&larr; Back'.html_safe, {controller: 'quizzes', action: 'manage'}, :class => "manage-back-link"  %>
    </div>
  </div>
</div>

app/views/languages/new.html.erb
<% content_for :title, "Create New Language" %>
<div id="content" class="container language">
  <div class="row no-margin">
    <h2 class="section-header col s10 m10  offset-s1 offset-m1 offset-l2">New Language</h2>
  </div>

  <%= render 'form' %>

  <div class="row">
    <div class="col s10  offset-s1 offset-m1 offset-l2">
      <%= link_to '&larr; Back'.html_safe, languages_path %>
    </div>
  </div>
</div>