config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  get 'languages/index'
  post 'languages/destroy_logo'

  post 'snippets/:id/update_active', to: 'snippets#update_active'
  post 'snippets/:id/update_snippet', to: 'snippets#update_snippet'
  post 'snippets/:id/add_snippet', to: 'snippets#add_snippet'
  post 'categories/:id/update_active', to: 'categories#update_active'


  get 'categories/index'

  get 'study/index'

  get 'quizzes/index'
  get 'quizzes/new', to: 'quizzes#new'
  get 'quizzes/question', to: 'quizzes#question'
  get 'quizzes/manage', to: 'quizzes#manage'
  get 'quizzes/answer', to: 'quizzes#answer'
  get 'welcome/index'

  resources :snippets

  resources :languages

  resources :categories

  resources :quizzes

  root 'quizzes#new'
  #get '/quizzes', to: 'controller_name#press'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  validates :name, :user, presence: true
  validates :name, length: { in: 1..50}, uniqueness: { scope: :user_id }

  has_many :snippets, :dependent => :restrict_with_error

  after_create :init

  def init
    self.active  ||= true   #will set the default value only if it's nil
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, Category
    @categories = Category.accessible_by(current_ability)
  end

  def show
    redirect_to categories_path
  end

  def new
    @category = Category.new
    authorize! :new, @category
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    @category.default = false
    authorize! :create, @category

    if @category.save

      #If admin we need to store data to be used later for default language look up
      if current_user.admin == true
        @category.default = true;
        @category.update_attributes(
          :default => true,
          :default_id => @category.id
          )
      end

      @categories = Category.accessible_by(current_ability)
      redirect_to categories_path
    else
      @errors = @category.errors
      render 'new'
    end
  end

  def edit
    redirect_to categories_path
  end

  def update
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      @categories = Category.accessible_by(current_ability)
      redirect_to categories_path
    else
      # @errors = @category.errors
      # @errors[:base] << "Categories cannot be destroyed if they are still being used to describe any code snippets."
      respond_to do |format|
        format.html { redirect_to categories_path, alert: "Categories cannot be destroyed if they are still being used to describe any code snippets."}
      end
    end
  end

  def update_active
    @category = Category.find(params[:id])

    # if @category.update_attributes(:active => params[:active])
    if @category.update_attributes(:active => params[:active])
      # data = {:message => "Worked! " + params[:active]}
      # render :json => data, :status => :ok
    else
      # data = {:message => "Not worked! " + params[:active]}
      # render :json => data, :status => :ok
    end
  end

  private
    def category_params
      params.require(:category).permit(:name, :active)
    end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/index.html.erb
<% content_for :title, "Manage Categories" %>
<div class="container category" id="content">
  <h2 class="section-header center-align">Categories</h2>
  <table class="highlight">
    <thead>
      <tr>
        <th>Category Name</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td class="min-width"><%= link_to 'Remove', category_path(category),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </br>
  <div class="row center">
    <div class="col s12">
      <%= link_to 'New Category', new_category_path, :class => 'btn-large waves-effect waves-light blue' %>
    </div>
  </div>
  <div class="row no-margin">
    <div class="col s12">
      <%= link_to '&larr; Back'.html_safe, {controller: 'quizzes', action: 'manage'}, :class => "manage-back-link"  %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, "Create New Category" %>
<div id="content" class="container language">
  <div class="row no-margin">
    <h2 class="section-header col s10 m10  offset-s1 offset-m1 offset-l2">New Category</h2>
  </div>
<%= form_for @category do |f| %>
  <div class="row">
    <div class="section input-field col s8 m6 l4 offset-s1 offset-m1 offset-l2">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col s10 offset-s1 offset-m1 offset-l2">
        <%= f.button :class => 'btn-large waves-effect waves-light blue white-text btn btn-flat'%>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col s10  offset-s1 offset-m1 offset-l2">
      <%= link_to '&larr; Back'.html_safe, categories_path %>
    </div>
  </div>
</div>