config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  get 'languages/index'
  post 'languages/destroy_logo'

  post 'snippets/:id/update_active', to: 'snippets#update_active'
  post 'snippets/:id/update_snippet', to: 'snippets#update_snippet'
  post 'snippets/:id/add_snippet', to: 'snippets#add_snippet'
  post 'categories/:id/update_active', to: 'categories#update_active'


  get 'categories/index'

  get 'study/index'

  get 'quizzes/index'
  get 'quizzes/new', to: 'quizzes#new'
  get 'quizzes/question', to: 'quizzes#question'
  get 'quizzes/manage', to: 'quizzes#manage'
  get 'quizzes/answer', to: 'quizzes#answer'
  get 'welcome/index'

  resources :snippets

  resources :languages

  resources :categories

  resources :quizzes

  root 'quizzes#new'
  #get '/quizzes', to: 'controller_name#press'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Snippet, user_id: user.id
    can :new, Snippet
    can :manage, Category, user_id: user.id
    can :new, Category
    can :manage, Language, user_id: user.id
    can :new, Language
    can :manage, Implementation, :snippet => { user_id: user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  validates :name, :user, presence: true
  validates :name, length: { in: 1..50}, uniqueness: { scope: :user_id }

  has_many :snippets, :dependent => :restrict_with_error

  after_create :init

  def init
    self.active  ||= true   #will set the default value only if it's nil
  end
end

app/models/implementation.rb
class Implementation < ApplicationRecord
  belongs_to :snippet, inverse_of: :implementations
  belongs_to :language

  validates :snippet, :language, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user

  validates :name, :user, presence: true
  validates :name, length: { in: 1..20}, uniqueness: { scope: :user_id }

  has_many :implementations, inverse_of: :language, :dependent => :destroy

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, presence: true,
    :content_type => { :content_type => /\Aimage/ },
    size: { in: 0..300.kilobytes }
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user

  validates :user, :language_id, presence: true

  has_many :quiz_snippets, inverse_of: :quiz, :dependent => :destroy

  accepts_nested_attributes_for :quiz_snippets, allow_destroy: true
end

app/models/quiz_snippet.rb
class QuizSnippet < ApplicationRecord
  belongs_to :quiz, inverse_of: :quiz_snippets

  validates :snippet_id, presence: true

  belongs_to :snippet
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user

  validates :title, :user, presence: true
  validates :title, length: { in: 1..50 }, uniqueness: { scope: :user_id }
  validates :runtime_complexity, length: { maximum: 30 }
  validates :space_complexity, length: { maximum: 30 }

  has_many :implementations, inverse_of: :snippet, :dependent => :destroy
  has_many :quiz_snippets

  accepts_nested_attributes_for :implementations, allow_destroy: true

  after_create :init

  def init
    self.active  ||= true   #will set the default value only if it's nil
  end

end

app/models/user.rb
class User < ApplicationRecord

  validates :email, :password, presence: true
  validates :email, length: { in: 4..40}, uniqueness: true
  validates :password, length: { minimum: 5}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :quizzes, dependent: :destroy
  has_many :snippets, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :languages, dependent: :destroy
  has_one :user_detail, dependent: :destroy
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # File helps to define some conventions to be used for this project

  # Things to check
  # 1. Are you making sure that a user is authorized?
  #   authorize! :read, @article
  #   load_and_authorize_resource will perform it for every action
  # 2.


  def list
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @subjects = Subject.all
  end

  def book_params
    params.require(:books).permit(:title, :price, :subject_id, :description)
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to :action => 'list'
    else
      @subjects = Subject.all
      render :action => 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @subjects = Subject.all
  end

  def book_param
    params.require(:book).permit(:title, :price, :subject_id, :description)
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_param)
      redirect_to :action => 'show', :id => @book
    else
      @subjects = Subject.all
      render :action => 'edit'
    end
  end

  def delete
    Book.find(params[:id]).destroy
    redirect_to :action => 'list'
  end

  def show_subjects
    @subject = Subject.find(params[:id])
  end

end

app/controllers/study_controller.rb
class StudyController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_customization_status(snippet)
    status = "Default"
    if snippet.default
      if snippet.update_available
        status = "Update Available"
      elsif snippet.modified
        status = "Modified"
      end
    else
      status = "Modified"
    end
    status
  end

  def get_snippet_category(snippet)
    category = Category.find_by_id(snippet.category_id)
    category_name = ""

    if !category.blank?
      category_name = category.name
    end
    category_name
  end

  def get_implementation_count(snippet)
    snippet.implementations.where.not(:code => "").count
  end

  def get_language(implementation, snippet_id)
    language = Language.accessible_by(current_ability).find_by_id(implementation.language_id)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg, class: ["alert", "alert-danger"]) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <!-- Modal Structure -->
    <div class="modal error-modal">
      <div class="modal-header">
        <h3 class="section-header white-text">Hey, guess what?</h3>
      </div>
      <div class="modal-content">
        <b>
          #{sentence}
        </b>
        #{messages}
      </div>
      <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect btn-flat">Got It!</a>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/language_helper.rb
module LanguageHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/study_helper.rb
module StudyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_save_modal.html.erb
<!-- Modal Structure -->
<div id="save-modal" class="modal">
  <div class="modal-header">
    <h3 class="section-header white-text">Good Show!</h3>
  </div>
  <div class="modal-content">
    <p>It seems you've built up the ol "Ctrl + S" muscle.</p>
    <% unless user_signed_in? %>
    <p>If you make an account (no monetization) you can add your own snippets of code to practice... and those will actually be saved.</p>
    <p>Sign up <%= link_to("here", new_user_registration_path, :class => '') %>.</p>
    <% else %>
    <p>You can add or customize your user content <%= link_to("here", quizzes_manage_path, :class => '') %>.</p>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect btn-flat">Got It!</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title><%= content_for?(:title) ? content_for(:title) : "Hello Around the World!" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'materialize' %>
    <%= favicon_link_tag "logo/logo-blue-16.png" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- CSS  -->
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/> -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- TODO: Evaluate, may already have -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  </head>
  <body>
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container">
        <ul id="logo-container" class="left">
          <li>
            <%= link_to image_tag("logo/logo-white-64.png"), root_path, :id => 'logo-image', :class => 'brand-logo' %>
          </li>
          <li>
            <%= link_to "Hello Around the World!", root_path, :id => 'logo-text', :class => 'brand-logo' %>
          </li>
        </ul>
        <% if user_signed_in? %>
        <!-- <ul class="right hide-on-med-and-down"> -->
        <ul class="right">
          <!-- <li><%= link_to "Study", study_index_path %></li> -->
          <li><%= link_to "Quiz", quizzes_new_path %></li>
          <li>
            <a id="nav-dropdown-menu" class='dropdown-button' href='#' data-activates='user-dropdown'><strong><%= current_user.email %></strong></a>
            <ul id='user-dropdown' class='dropdown-content'>
              <li><%= link_to 'Edit Profile', edit_user_registration_path, :id => 'nav-edit-profile', :class => 'dropdown-item' %></li>
              <li class="divider"></li>
              <li><%= link_to 'Manage Snippets', snippets_path, :id => 'nav-snippets', :class => 'dropdown-item'  %></li>
              <li><%= link_to 'Manage Categories', categories_path, :id => 'nav-categories', :class => 'dropdown-item'  %></li>
              <li><%= link_to 'Manage Languages', languages_path, :id => 'nav-languages', :class => 'dropdown-item'  %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :id => 'nav-logout', :class => 'navbar-link dropdown-item'  %></li>
            </ul>
          </li>
        </ul>
        <% else %>
        <ul class="right">
          <li><%= link_to "Quiz", quizzes_new_path, :id => 'nav-quiz' %></li>
          <!--<li><%= link_to "Study", study_index_path %></li> -->
          <li><%= link_to "Login", new_user_session_path, :id => 'nav-login' %></li>
          <li><%= link_to "Sign up", new_user_registration_path, :id => 'nav-register' %></li>
        </ul>
        <% end %>
        <ul id="nav-mobile" class="side-nav">
          <li><a href="#">Navbar Link</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
    <main class="section no-pad-bot main-section" id="index-banner">
      <% if(!@errors.nil? && @errors.messages.any?) || !flash.empty?%>
      <!-- Modal Structure -->
      <div class="modal error-modal">
        <div class="modal-header">
          <% if(!@errors.nil? && @errors.messages.any?)%>
            <h3 class="section-header white-text">Aw, shucks!</h3>
          <% else %>
            <h3 class="section-header white-text">Hey, guess what?</h3>
          <% end %>
        </div>
        <div class="modal-content">
          <% if(!@errors.nil? && @errors.messages.any?)%>
          <b>
          <%= pluralize(@errors.count, "error") %> prohibited
          this snippet from being saved.
          </b>
          <% end %>
          <% if(!@errors.nil? && @errors.messages.any?)%>
            <% @errors.messages.each do |attribute, msg| %>
              <% msg.each do |val| %>
                <p class="alert alert-danger"><%= attribute.to_s.camelize %>: <%= val %></p>
              <% end %>
            <% end %>
          <% else %>
            <% flash.each do |key, value| %>
              <p class="alert alert-danger"><%= value %></p>
            <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
          <a href="#!" class=" modal-action modal-close waves-effect btn-flat">Got It!</a>
        </div>
      </div>
      <% end %>
      <!-- Begin Content -->
      <%= yield %>
    </main>
    <footer class="page-footer blue lighten-1">
      <div class="footer-copyright">
        <div class="container">
        Made by <a class="blue-text text-lighten-3" href="https://github.com/Zarkana">Joseph Campbell</a>
        <a class="blue-text text-lighten-3 right" href="https://github.com/Zarkana/hello-around-the-world">What is, Hello Around The World?</a>
        </div>
      </div>
    </footer>
    <!--  Scripts-->
    <!-- <script src="materialize-src/js/materialize.js"></script>
    <script src="materialize-src/js/init.js"></script>
    <script src="scripts/main.js"></script> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'materialize' %>
    <%= javascript_include_tag 'init' %>
    <%= javascript_include_tag 'main' %> -->
  </body>
</html>